---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-project
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: medicure
          image: kunalsawant29/healthcare:1.0
          ports:
           - containerPort: 8084
           - name: http-web-app-01
