apiVersion: v1
kind: Service
metadata:
    name: healthcare-service
spec:
  type: NodePort  
  selector:
    app: healthcare
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 31616    
