apiVersion: v1
kind: Service
metadata:
    name: healthcare-service
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 31616
  selector:
    component: healthcare    
